apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  DB_HEALTHCHECK_USER: "healthcheck"

  # Mysql init script
  init.sql: |
      CREATE USER IF NOT EXISTS 'healthcheck'@'%' IDENTIFIED BY 'p@ssword';
      GRANT USAGE ON *.* TO 'healthcheck'@'%';
      
      SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
      SET time_zone = "+00:00";

      CREATE DATABASE IF NOT EXISTS message;
      USE message;
      
      CREATE TABLE messages (
        id INT AUTO_INCREMENT PRIMARY KEY,
        message TEXT
      );

      CREATE USER IF NOT EXISTS 'message'@'%' IDENTIFIED BY 'message';
      GRANT ALL PRIVILEGES ON message.* TO 'message'@'%';
      ALTER USER 'message'@'%' IDENTIFIED BY 'message';
      FLUSH PRIVILEGES;
